### ISSUE TITLE
Article save bug

### ISSUE THREAD

**Issue by fastAsF** [dillionmegida/thewebfor5#13]
## Expected Behavior
To save an article.

## Current Behavior
I can't save an article if I select a tag.

## Possible Solution
Push the article id to the localstorage array.

## Steps to Reproduce
Save an article on the main page then select the "javascript" tag and try to save an article. After this check for saved articles. It says I have saved two posts but actually shows me one.
Picture of localstorage data:
![possible_bug](https://user-images.githubusercontent.com/51188711/82257225-f2a00800-9957-11ea-9071-db52eab66069.PNG)

**Comment by fastAsF** [comment]
You can also find this bug if you search for an article @dillionmegida

**Comment by dillionmegida** [comment]
Hello there, thank you so much for your contribution.

I've fixed the issue. I was not providing the id of the articles on the search page and tag page. That's the reason it was null.

It should work perfectly now. If you find any issue, please let me know. Thank you.
